### PR TITLE
Show idle resources as grey

### PR DESCRIPTION
**Pull request by Joaquin6**
*Issue #102*

*Description of changes:*

### Idle Resources

- Resources are now being labeled as `IDLE` or `RUNNING` state in DynamoDB.
- We leverage the running timer of `update_nodes` and inherit the API responses by boto3 to tag nodes.
- On each request to fetch events from the UI - in addition, make a request to fetch a group of idle and running resources.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by JimTharioAmazon** [comment]
Hi there, I'm seeing two things needing work before merging this one into the trunk.

1. I'm getting inconsistent results transitioning from running/idle/running with MediaLive channels. I can't quite yet pin down the conditions to recreate yet. I have both single and dual pipeline channels, but I don't see how that would factor in.

2. The 'data' payload sent with each entry in the state API call is large. I'm concerned about scale problems if it's monitoring several hundred channels with MediaLive and CloudFront distributions at a high interval. Can it send only the items needed for evaluating the state?

Thanks!

**Comment by Joaquin6** [comment]
spoke with joan. 
just resolved a merge conflict. Consuming the latest from upstream.

**Comment by Joaquin6** [comment]
Phew! Conflicts are fixed here!

**Comment by Joaquin6** [comment]
@JimTharioAmazon @morjoan Closing this PR and continuing on PR #140

**Pull request closed without merging**
